### ISSUE TITLE
How to update the code to python 3

### ISSUE THREAD

**Issue by Mica7812** [onuryilmaz/turkish-pos-tagger#4]
It seems like this code was designed for an older version of python. How am I supposed to "translate" this into python 3+?

Traceback (most recent call last):
  File "/home/mica/Downloads/turkish-pos-tagger-master/test.py", line 1, in <module>
    from pos_tagger import tag
  File "/home/mica/Downloads/turkish-pos-tagger-master/pos_tagger.py", line 22, in <module>
    myTagger=yaml.load(f)
  File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 72, in load
    return loader.get_single_data()
  File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 37, in get_single_data
    return self.construct_document(node)
  File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 41, in construct_document
    data = self.construct_object(node)
  File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 86, in construct_object
    data = constructor(self, node)
  File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 414, in construct_undefined
    node.start_mark)
yaml.constructor.ConstructorError: could not determine a constructor for the tag '!nltk.BrillTagger'
  in "my_tagger.yaml", line 1, column 1

I get this from running pos tagger

**Comment by Mica7812** [comment]
Was an error
